<li class="mainlevel">
          <a href="{dede:field name='typeurl'/}" class="nav nav_03" target="_blank">{dede:field name='typename'/}</a>
        <ul id="sub_04" class="pro hide">
          <li id="pro_box">
            <div id="menu_products">



            {dede:channel type='son' noself='yes'}
              {dede:channel type='son' noself='yes'}
              <li><a href="[field:typelink/]">[field:typename/]</a> </li>
              {/dede:channel}

              <dl id="l_110">
                <dt>
                  <h2><a href="[field:typelink/]" title="[field:typename/]" target="_blank">[field:typename/]</a></h2>
                </dt>
        <dd id="hot"><a href="http://www.weilaijixie.com/espsj.html" title="颚式破碎机" target="_blank">●&nbsp;&nbsp;颚式破碎机</a><img src="http://www.weilaijixie.com/images1312/dd_bg_16.jpg" /></dd>
        <dd id="hot"><a href="http://www.weilaijixie.com/obespsj.html" title="欧版颚式破碎机" target="_blank">●&nbsp;&nbsp;欧版颚式破碎机</a><img src="http://www.weilaijixie.com/images1312/dd_bg_16.jpg" /></dd>
        <dd id="hot"><a href="http://www.weilaijixie.com/fjpsj.html" title="反击式破碎机" target="_blank">●&nbsp;&nbsp;反击式破碎机</a><img src="http://www.weilaijixie.com/images1312/dd_bg_16.jpg" /></dd>
        <dd><a href="http://www.weilaijixie.com/obfjp.html" title="欧版反击式破碎机" target="_blank">●&nbsp;&nbsp;欧版反击式破碎机</a></dd>
        <dd id="hot"><a href="http://www.weilaijixie.com/thyzp.html" title="弹簧圆锥破碎机" target="_blank">●&nbsp;&nbsp;弹簧圆锥破碎机</a><img src="http://www.weilaijixie.com/images1312/dd_bg_16.jpg" /></dd>
        <dd id="hot"><a href="http://www.weilaijixie.com/yyyzp.html" title="液压圆锥破碎机" target="_blank">●&nbsp;&nbsp;液压圆锥破碎机</a></dd>
         <dd id="hot"><a href="http://www.weilaijixie.com/zcspsj" title="重锤式破碎机" target="_blank">●&nbsp;&nbsp;重锤式破碎机</a><img src="http://www.weilaijixie.com/images1312/dd_bg_16.jpg" /></dd>
        <dd id="hot"><a href="http://www.weilaijixie.com/cspsj.html" title="锤式破碎机" target="_blank">●&nbsp;&nbsp;锤式破碎机</a><img src="http://www.weilaijixie.com/images1312/dd_bg_16.jpg" /></dd>
        <dd><a href="http://www.weilaijixie.com/dgpsj.html" title="对辊破碎机" target="_blank">●&nbsp;&nbsp;对辊破碎机</a></dd>
        <dd><a href="http://www.weilaijixie.com/fhpsj.html" title="立轴式复合破碎机" target="_blank">●&nbsp;&nbsp;立轴式复合破碎机</a></dd>
        <dd id="hot"><a href="http://www.weilaijixie.com/ydpsz.html" title="移动破碎站" target="_blank">●&nbsp;&nbsp;移动破碎站</a></dd>
        <dd><a href="http://www.weilaijixie.com/xspsj.html" title="箱式破碎机" target="_blank">●&nbsp;&nbsp;箱式破碎机</a></dd>             
              </dl>
            {/dede:channel}





              <div class="vline" style="height:255px;"></div>
              <dl id="l_270">
                <dt>
                <h2><a href="http://www.weilaijixie.com/zssb.html" title="制砂设备" target="_blank">制砂设备</a></h2>
                </dt>
        <dd id="hot"><a href="http://www.weilaijixie.com/vsizsj.html" title="VSI制砂机" target="_blank">●&nbsp;&nbsp;VSI制砂机</a><img src="http://www.weilaijixie.com/images1312/dd_bg_16.jpg" /></dd>
        <dd id="hot"><a href="http://www.weilaijixie.com/5xzsj.html" title="5X冲击式制砂机" target="_blank">●&nbsp;&nbsp;5X冲击式制砂机</a><img src="http://www.weilaijixie.com/images1312/dd_bg_16.jpg" /></dd>
        <dd><a href="http://www.weilaijixie.com/pclzsj.html" title="PCL制砂机" target="_blank">●&nbsp;&nbsp;PCL制砂机</a></dd>
        <dd id="hot"><a href="http://www.weilaijixie.com/lsxsj.html" title="轮式洗砂机" target="_blank">●&nbsp;&nbsp;轮式洗砂机</a><img src="http://www.weilaijixie.com/images1312/dd_bg_16.jpg" /></dd>
        <dd><a href="http://www.weilaijixie.com/lxxsj.html" title="螺旋洗砂机" target="_blank">●&nbsp;&nbsp;螺旋洗砂机</a></dd>
        <dd id="hot"><a href="http://www.weilaijixie.com/yzds.html" title="圆振动筛" target="_blank">●&nbsp;&nbsp;圆振动筛</a><img src="http://www.weilaijixie.com/images1312/dd_bg_16.jpg" /></dd>
        <dd><a href="http://www.weilaijixie.com/xsj.html" title="细碎机" target="_blank">●&nbsp;&nbsp;细碎机</a></dd>
        <dd id="hot"><a href="http://www.weilaijixie.com/xshsj.html" title="细砂回收机" target="_blank">●&nbsp;&nbsp;细砂回收机</a></dd>
        <dd><a href="http://www.weilaijixie.com/pdssj.html" title="皮带输送机" target="_blank">●&nbsp;&nbsp;皮带输送机</a></dd>
        <dd id="hot"><a href="http://www.weilaijixie.com/zdglj.html" title="振动给料机" target="_blank">●&nbsp;&nbsp;振动给料机</a></dd>
              </dl>
               <div class="vline" style="height:141px;"></div>
              <dl id="l_130">
                <dt>
                  <h2><a href="http://www.weilaijixie.com/ssscx.html" title="砂石料生产线" target="_blank">砂石料生产线</a></h2>
                </dt>
                <dd><a href="http://www.weilaijixie.com/shashiliaoshengchanxian/slscx.html" title="石料生产线" target="_blank">●&nbsp;&nbsp;石料生产线</a></dd>
        <dd><a href="http://www.weilaijixie.com/zhishashashengchanxian/zsscx.html" title="制砂生产线" target="_blank">●&nbsp;&nbsp;制砂生产线</a></dd>
        <dd><a href="http://www.weilaijixie.com/zzyscx/zzyscx.html" title="珍珠岩生产线" target="_blank">●&nbsp;&nbsp;珍珠岩生产线</a></dd>
              </dl>
              <div class="vline" style="height:230px;"></div>
              <dl id="l_145">
                <dt>
                  <h2><a href="http://www.weilaijixie.com/xksb.html" title="选矿设备" target="_blank">选矿设备</a></h2>
                </dt>
                <dd id="hot"><a href="http://www.weilaijixie.com/qmj.html" title="球磨机" target="_blank">●&nbsp;&nbsp;球磨机</a><img src="http://www.weilaijixie.com/images1312/dd_bg_16.jpg" /></dd>
        <dd><a href="http://www.weilaijixie.com/fxj.html" title="浮选机" target="_blank">●&nbsp;&nbsp;浮选机</a></dd>
        <dd id="hot"><a href="http://www.weilaijixie.com/hgj.html" title="烘干机" target="_blank">●&nbsp;&nbsp;烘干机</a><img src="http://www.weilaijixie.com/images1312/dd_bg_16.jpg" /></dd>
        <dd><a href="http://www.weilaijixie.com/fjj.html" title="分级机" target="_blank">●&nbsp;&nbsp;分级机</a></dd>
        <dd><a href="http://www.weilaijixie.com/cxj.html" title="磁选机" target="_blank">●&nbsp;&nbsp;磁选机</a></dd>
        <dd><a href="http://www.weilaijixie.com/hzy.html" title="回转窑" target="_blank">●&nbsp;&nbsp;回转窑</a></dd>
        <dd><a href="http://www.weilaijixie.com/lmmfj.html" title="雷蒙磨粉机" target="_blank">●&nbsp;&nbsp;雷蒙磨粉机</a></dd>
        <dd><a href="http://www.weilaijixie.com/cxmfj.html" title="超细磨粉机" target="_blank">●&nbsp;&nbsp;超细磨粉机</a></dd>
              </dl>

              <div class="vline" style="height:230px;"></div>
              <dl id="l_146">
                <dt>
                <h2><a href="http://www.weilaijixie.com/xkgy/index.html" title="选矿工艺" target="_blank">选矿工艺</a></h2>
                </dt>
                <dd><a href="http://www.weilaijixie.com/xkgy/3075.html" title="铜矿石选矿工艺 " target="_blank">●&nbsp;&nbsp;铜矿石选矿工艺 </a></dd>

        <dd><a href="http://www.weilaijixie.com/xkgy/3090.html" title="铅锌矿石选矿工艺 " target="_blank">●&nbsp;&nbsp;铅锌矿石选矿工艺 </a></dd>

        <dd><a href="http://www.weilaijixie.com/xkgy/3081.html" title="锡矿石选矿工艺 " target="_blank">●&nbsp;&nbsp;锡矿石选矿工艺 </a></dd>

        <dd><a href="http://www.weilaijixie.com/xkgy/3084.html" title="镍矿石选矿工艺 " target="_blank">●&nbsp;&nbsp;镍矿石选矿工艺 </a></dd>

        <dd><a href="http://www.weilaijixie.com/xkgy/3078.html" title="钨矿石选矿工艺 " target="_blank">●&nbsp;&nbsp;钨矿石选矿工艺 </a></dd>

        <dd><a href="http://www.weilaijixie.com/xkgy/3083.html" title="钼矿石选矿工艺 " target="_blank">●&nbsp;&nbsp;钼矿石选矿工艺 </a></dd>

        <dd><a href="http://www.weilaijixie.com/xkgy/3085.html" title="锑矿石选矿工艺 " target="_blank">●&nbsp;&nbsp;锑矿石选矿工艺 </a></dd>

        <dd><a href="http://www.weilaijixie.com/xkgy/3082.html" title="汞矿石选矿工艺 " target="_blank">●&nbsp;&nbsp;汞矿石选矿工艺 </a></dd>

         <dd><a href="http://www.weilaijixie.com/xkgy/3093.html" title="钨钼铋多金属矿石选矿 " target="_blank">●&nbsp;&nbsp;钨钼铋多金属矿石选矿 </a></dd>

         <dd><a href="http://www.weilaijixie.com/xkgy/3077.html" title="金银矿石选矿工艺 " target="_blank">●&nbsp;&nbsp;金银矿石选矿工艺 </a></dd>

        <dd><a href="http://www.weilaijixie.com/xkgy/3091.html" title="钽铌矿石选矿工艺 " target="_blank">●&nbsp;&nbsp;钽铌矿石选矿工艺 </a></dd>

        <dd><a href="http://www.weilaijixie.com/xkgy/3074.html" title="铁矿石选矿工艺 " target="_blank">●&nbsp;&nbsp;铁矿石选矿工艺 </a></dd>

        <dd><a href="http://www.weilaijixie.com/xkgy/3076.html" title="锰矿石选矿工艺 " target="_blank">●&nbsp;&nbsp;锰矿石选矿工艺 </a></dd>

        <dd><a href="http://www.weilaijixie.com/xkgy/3088.html" title="铬铁矿选矿工艺 " target="_blank">●&nbsp;&nbsp;铬铁矿选矿工艺 </a></dd>

        <dd><a href="http://www.weilaijixie.com/xkgy/3103.html" title="萤石选矿工艺" target="_blank">●&nbsp;&nbsp;萤石选矿工艺</a></dd>

        <dd><a href="http://www.weilaijixie.com/xkgy/3104.html" title="硅石和硅砂选矿工艺 " target="_blank">●&nbsp;&nbsp;硅石和硅砂选矿工艺 </a></dd>

        <dd><a href="http://www.weilaijixie.com/xkgy/3102.html" title="叶腊石选矿工艺 " target="_blank">●&nbsp;&nbsp;叶腊石选矿工艺 </a></dd>

        <dd><a href="http://www.weilaijixie.com/xkgy/3095.html" title="高岭土选矿工艺 " target="_blank">●&nbsp;&nbsp;高岭土选矿工艺 </a></dd>

        <dd><a href="http://www.weilaijixie.com/xkgy/3096.html" title="铝土矿选矿工艺 " target="_blank">●&nbsp;&nbsp;铝土矿选矿工艺 </a></dd>

        <dd><a href="http://www.weilaijixie.com/xkgy/3098.html" title="石灰石选矿工艺 " target="_blank">●&nbsp;&nbsp;石灰石选矿工艺 </a></dd>

        <dd><a href="http://www.weilaijixie.com/xkgy/3101.html" title="石墨选矿工艺 " target="_blank">●&nbsp;&nbsp;石墨选矿工艺 </a></dd>

        <dd><a href="http://www.weilaijixie.com/xkgy/3097.html" title="膨润土选矿工艺 " target="_blank">●&nbsp;&nbsp;膨润土选矿工艺 </a></dd>

              </dl>

            </div>
          </li>
        </ul>
      </li>