<li class="mainlevel">
        <a href="[field:typelink/]" class="nav nav_02" target="_blank">[field:typename/]</a>
          <ul class="sv hide">
            <li><a href="http://www.weilaijixie.com/qiyejieshao/qiyejieshao.html">企业介绍</a> </li>
            <li><a href="http://www.weilaijixie.com/qiyejieshao/qiyewenhua.html">企业文化</a> </li>
            <li><a href="http://www.weilaijixie.com/qiyejieshao/fuwuchengnuo.html">服务承诺</a> </li>
            <li><a href="http://www.weilaijixie.com/qiyejieshao/flsm.html">法律声明</a> </li>
          </ul>
        </li>