<?php
$z[0]=Array("global","",310,336);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",377,404);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",444,474);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",575,607);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",674,706);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",764,796);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",868,900);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",976,1008);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("global","",1075,1107);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",1171,1203);
$z[9][4]['name']="cfg_templets_skin";
$z[10]=Array("global","",1242,1274);
$z[10][4]['name']="cfg_templets_skin";
$z[11]=Array("include","",1997,2032);
$z[11][4]['filename']="head.htm";
$z[12]=Array("global","",2136,2163);
$z[12][4]['name']="cfg_basehost";
$z[13]=Array("channelartlist","\r\n        <li class=\"mainlevel\">\r\n        <a href=\"{dede:field name='typeurl'/}\" class=\"nav nav_02\" target=\"_blank\">{dede:field name='typename'/}</a>\r\n          <ul class=\"sv hide\">\r\n            {dede:channel type='son' noself='yes'}\r\n              <li><a href=\"[field:typelink/]\">[field:typename/]</a> </li>\r\n              {/dede:channel}\r\n          </ul>\r\n        </li>\r\n      ",2230,2680);
$z[13][4]['typeid']="2,2";
$z[14]=Array("channelartlist","\r\n          <li class=\"mainlevel\">\r\n            <a class=\"nav nav_02\" href='{dede:field name='typeurl'/}'>{dede:field name='typename'/}</a>\r\n            <ul class=\"sv hide\">\r\n              {dede:channel type='son' noself='yes'}\r\n              <li><a href=\"[field:typelink/]\">[field:typename/]</a> </li>\r\n              {/dede:channel}\r\n            </ul>\r\n          </li>\r\n        ",13694,14152);
$z[14][4]['row']="7";
$z[14][4]['typeid']="8,9,10,11,12,13,14";

?>